### ISSUE TITLE
Spraied

### ISSUE THREAD

**Issue by 1j01** [boo1ean/tensify#1]
``` js
tensify("spray").past // "spraied" instead of "sprayed"
```

**Comment by 1j01** [comment]
So I'm using this package for another project now, and I'm getting "displaied" instead of "displayed",
so revisiting this issue...

The only place it adds "ied" is [here](https://github.com/boo1ean/tensify/blob/4b7e2bde6ad13191cf04fa1adaaded2c8dcbd113/src/inflector.js#L64-L65), and that's supposed to check [if it ends with a consonant and then y](https://github.com/boo1ean/tensify/blob/4b7e2bde6ad13191cf04fa1adaaded2c8dcbd113/src/inflector.js#L29-L33).

Turns out this is a problem in the `symbols` package. From the docs:

```js
// qwrtpasdfghjklmnbvcxz 
symbols.is_consonant(sym);
```

Can you spot the problam? 😅

**Comment by boo1ean** [comment]
I apologize for my illiteracy
`tensify@0.0.3`
